Нечего не понятно что делаю(((
EgroMan/2-nd-course-hw pull request #4
Opened 2023-06-19 16:37 UTC by EgroMan

2023-06-20 13:44 UTC, Mielilon requested changes

2023-06-20 13:44 UTC, Mielilon commented on script.js
> +let n =Number(prompt('Привет'));
Для решения данной задачи не нужно получать данные от пользователя. Сюда мы можем записать число 2, так как требуется вывести "Привет" 2 раза.

2023-06-20 13:44 UTC, Mielilon commented on script.js
> +let a = 2;
Предлагаю сделать переменную `a` стартовым значением. Запишем в нее 1, чтобы составить условие работы цикла.

2023-06-20 13:44 UTC, Mielilon commented on script.js
> +while (a = n){
Сейчас в условии происходит присвоение, из-за чего цикл будет бесконечным.
Нужно сравнить исходную точку (в нашем случае `а`) со значением конечной точки (в нашем случае `n`).

2023-06-20 13:44 UTC, Mielilon commented on script.js
> +    i++;
Переменная не была объявлена, выбросит ошибку. Нужно использовать существующую.

2023-06-20 13:44 UTC, Mielilon commented on script.js
> +for (let i = 0; i <= b; i++) {
Нужно поправить условие. Сейчас будет выведено больше, чем нужно. Однако само решение можно назвать почти полностью верным.

2023-06-20 13:44 UTC, Mielilon commented on script.js
> +var obj = {Коля: '200', Вася:'300', Петя: '400'};
`var` – устаревшее ключевое слово, нужно заменить его во всем проекте.

2023-06-20 13:44 UTC, mielilon commented on script.js
> +for(key in obj){
Не стоит делать для решения вложенный цикл. Нам достаточно воспользоваться одним.

2023-06-20 13:44 UTC, mielilon commented on script.js
> +document.write();(n);
Подозреваю, что тут (как и на строчке ниже) должен быть вывод в консоль.
Требуется поправить.

2023-06-20 13:44 UTC, mielilon commented on script.js
> +    i6 += 6;
Данная строчка нам не нужна, так как манипуляции над переменной производятся в условии цикла.

2023-06-20 13:44 UTC, mielilon commented on script.js
> +    alert ('Сегодня пятница, ${i6} число. Необходимо подготовить отчет.')
Вывод не сработает, так как использованы некорректные для интерполяции кавычки. Нужно поправить.

2023-06-21 13:17 UTC, mielilon commented on script.js
> +for (i6 = 1; i6 < 31; i6 += 7){
Тут затерялось объявление переменной i6, нужно добавить.

2023-06-21 13:17 UTC, Mielilon commented on script.js
> +for (var i = 0; i < 2; i++) {
Не стоит использовать `var` для объявления переменной, так как это устаревшее ключевое слово. Лучше заменить его на `let`

2023-06-23 18:54 UTC, merged